# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, default=b'', max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, default=b'', max_length=200)),
                ('zip_code', models.CharField(blank=True, default=b'', max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('website', models.CharField(blank=True, default=b'', max_length=200)),
                ('phone', models.CharField(blank=True, default=b'', max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('localities', models.CharField(blank=True, default=b'', max_length=400)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner')),
            ],
        ),
    ]
