# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(default=b'default_image', upload_to=b'categories')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0, verbose_name=b'Position')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', sorl.thumbnail.fields.ImageField(upload_to=b'products')),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name=b'Position')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('tearsheet', models.FileField(default=b'no_image.png', upload_to=b'product_tear_sheets')),
                ('tearsheet_metric', models.FileField(blank=True, default=b'', upload_to=b'product_tear_sheets_metric')),
                ('dimensions', tinymce.models.HTMLField(blank=True, default=b'')),
                ('description', tinymce.models.HTMLField(blank=True, default=b'')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
