# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('body', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', sorl.thumbnail.fields.ImageField(upload_to=b'carousel')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_header_left', models.CharField(max_length=200)),
                ('contact_header_middle', models.CharField(max_length=200)),
                ('contact_header_right', models.CharField(max_length=200)),
                ('contact_body_left', tinymce.models.HTMLField()),
                ('contact_body_middle', tinymce.models.HTMLField()),
                ('contact_body_right', tinymce.models.HTMLField()),
                ('social_header', models.CharField(max_length=200)),
                ('social_body', tinymce.models.HTMLField()),
                ('newsletter_header', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MenuContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_label', models.CharField(max_length=200)),
                ('about_label', models.CharField(max_length=200)),
                ('retailers_label', models.CharField(max_length=200)),
                ('partner_label', models.CharField(max_length=200)),
                ('login_label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_body', tinymce.models.HTMLField(default=b'')),
            ],
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='home_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.HomeContent'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
