# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucontent',
            name='documents_label',
            field=models.CharField(default='Documents', max_length=200),
            preserve_default=False,
        ),
    ]
