# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_menucontent_documents_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menucontent',
            old_name='documents_label',
            new_name='resources_label',
        ),
    ]
