# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20161220_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucontent',
            name='resources_label',
        ),
    ]
