# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_menucontent_resources_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucontent',
            name='resources_label',
            field=models.CharField(default='Resources', max_length=200),
            preserve_default=False,
        ),
    ]
