# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_menucontent_resources_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('body', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='menucontent',
            name='contract_label',
            field=models.CharField(default='Contract', max_length=200),
            preserve_default=False,
        ),
    ]
